import { Metadata } from "next";

import "./globals.css";
import { AppProviders } from "./providers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "RoadMap-Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <AppProviders>
          <main className="flex-1 p-4 overflow-y-auto">
            <Toaster />
            {children}
          </main>
        </AppProviders>
      </body>
    </html>
  );
}
